name: mobile
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9

  # State Management & Routing
  get: ^4.6.6

  # Networking
  dio: ^5.3.4

  # Storage
  get_storage: ^2.1.1

  # Utils
  intl: ^0.18.1
  permission_handler: ^11.0.1
  geolocator: ^10.1.0
  url_launcher: ^6.1.14
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    # - assets/images/
